import Image from "next/image";
import Link from "next/link";
import { ArrowRight, BrainCircuit, CloudSun, Gauge, Radar, ShieldCheck, Sparkles, Waves } from "lucide-react";

const signals = [
  ["01", "Observe", "NWP · AI · ensembles · stations · satellites", Radar],
  ["02", "Understand", "Regime, season, lead time and model health", BrainCircuit],
  ["03", "Decide", "One calibrated forecast with uncertainty explained", Gauge],
] as const;

export default function LandingPage() {
  return <main className="min-h-screen overflow-hidden bg-navy-950 text-slate-100">
    <section className="relative min-h-[760px] border-b border-cyan-300/10"><Image src="/images/aeris-intelligence-hero.png" alt="Satellite-enabled weather intelligence over India" fill priority className="object-cover object-center opacity-70" /><div className="absolute inset-0 bg-[radial-gradient(circle_at_74%_42%,rgba(34,211,238,.18),transparent_30%),linear-gradient(90deg,#040814_10%,#040814_e8_46%,#040814_75%)]" /><div className="aeris-grid absolute inset-0 opacity-50" />
      <header className="relative z-10 mx-auto flex max-w-7xl items-center justify-between px-6 py-6"><Link href="/" className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl border border-cyan-300/40 bg-cyan-400/10 text-cyan-200"><Waves size={22} /></div><div><div className="text-lg font-bold tracking-[.18em] text-white">AERIS</div><div className="text-[10px] tracking-[.18em] text-cyan-200/70">FORECAST INTELLIGENCE</div></div></Link><div className="hidden items-center gap-6 text-sm text-slate-300 md:flex"><Link href="/architecture" className="hover:text-cyan-200">How it works</Link><Link href="/about" className="hover:text-cyan-200">Methodology</Link><Link href="/login" className="rounded-full border border-cyan-300/30 px-4 py-2 text-cyan-100 transition hover:bg-cyan-300/10">Secure console</Link></div></header>
      <div className="relative z-10 mx-auto max-w-7xl px-6 pb-24 pt-24 md:pt-32"><div className="max-w-3xl"><div className="mb-6 inline-flex items-center gap-2 rounded-full border border-amber-300/30 bg-amber-300/10 px-3 py-1 text-xs font-medium text-amber-100"><Sparkles size={13} /> SIH 2026 · PS 26081 · Disaster Management</div><p className="text-sm font-medium tracking-[.24em] text-cyan-300">ADAPTIVE ENSEMBLE &amp; REGIME INTELLIGENCE</p><h1 className="mt-5 text-5xl font-semibold leading-[1.04] tracking-tight text-white md:text-7xl">When weather changes, <span className="text-cyan-300">trust must adapt.</span></h1><p className="mt-7 max-w-2xl text-lg leading-8 text-slate-300">AERIS turns competing forecast signals into one explainable, context-aware decision layer for a safer, climate-resilient India.</p><div className="mt-9 flex flex-wrap gap-3"><Link href="/login" className="group inline-flex items-center gap-2 rounded-xl bg-cyan-300 px-5 py-3 text-sm font-bold text-navy-950 transition hover:bg-cyan-200">Sign in to console <ArrowRight size={16} className="transition group-hover:translate-x-1" /></Link><Link href="/architecture" className="rounded-xl border border-white/20 bg-white/5 px-5 py-3 text-sm font-semibold text-white backdrop-blur transition hover:bg-white/10">See the AERIS flow</Link></div><p className="mt-5 text-xs text-slate-400">Demonstration / benchmark data only. Designed for decision support, not a replacement for official warnings.</p></div></div>
      <div className="relative z-10 mx-auto grid max-w-7xl gap-3 px-6 pb-8 md:grid-cols-3">{signals.map(([n, title, desc, Icon]) => <div key={title} className="flex gap-4 rounded-2xl border border-white/10 bg-navy-950/60 p-4 backdrop-blur"><span className="text-xs font-bold text-cyan-300">{n}</span><Icon className="mt-0.5 text-cyan-200" size={20} /><div><h2 className="font-semibold text-white">{title}</h2><p className="mt-1 text-xs leading-5 text-slate-400">{desc}</p></div></div>)}</div>
    </section>
    <section className="mx-auto max-w-7xl px-6 py-20"><div className="grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><div><p className="text-sm font-semibold tracking-[.2em] text-cyan-300">WHY AERIS</p><h2 className="mt-4 text-3xl font-semibold text-white">Not another weather dashboard.</h2><p className="mt-4 leading-7 text-slate-400">AERIS is a trust engine: it learns which forecast source deserves influence for a specific place, variable, lead time and atmospheric regime—and makes that decision visible.</p></div><div className="grid gap-4 sm:grid-cols-2"><Feature icon={CloudSun} title="Multi-model reasoning" text="NWP, AI and ensemble forecasts are blended instead of blindly averaged." /><Feature icon={ShieldCheck} title="Forecast Reliability Score" text="Value, confidence and disagreement are kept distinct for safer decisions." /><Feature icon={BrainCircuit} title="Regime-aware trust" text="Weights shift when monsoon dynamics, season and regional context shift." /><Feature icon={Gauge} title="Decision-ready output" text="Extreme-event intelligence and counterfactual simulations turn uncertainty into action." /></div></div></section>
  </main>;
}

function Feature({ icon: Icon, title, text }: { icon: typeof CloudSun; title: string; text: string }) { return <div className="rounded-2xl border border-cyan-900/40 bg-navy-900 p-5"><Icon className="text-cyan-300" size={22} /><h3 className="mt-5 font-semibold text-white">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-400">{text}</p></div>; }
