import Link from "next/link";
import { ArrowDown, ArrowRight, BrainCircuit, CheckCircle2, CloudRain, Database, Eye, Gauge, HeartPulse, Radar, ShieldAlert, Sparkles } from "lucide-react";

const inputs = [["NWP models", "GFS · ECMWF · NCMRWF", CloudRain], ["AI / ML models", "Learned pattern signals", BrainCircuit], ["Ensembles", "Spread as useful evidence", Radar], ["Observations", "Station / satellite / radar", Eye]] as const;
const intelligence = [["Harmonise", "Align time, grid, units and quality flags", Database], ["Read context", "Region · season · lead · weather regime", Sparkles], ["Measure trust", "Skill memory · health · disagreement", HeartPulse], ["Blend with guardrails", "Non-negative weights that sum to one", Gauge]] as const;

export default function ArchitecturePage() {
  return <main className="aeris-grid min-h-screen bg-navy-950 px-6 py-12 text-slate-100"><div className="mx-auto max-w-7xl"><Link href="/" className="text-sm text-cyan-300 hover:text-cyan-200">← AERIS home</Link><div className="mt-8 max-w-3xl"><p className="text-sm font-semibold tracking-[.2em] text-cyan-300">SYSTEM STORY</p><h1 className="mt-3 text-4xl font-semibold text-white md:text-5xl">From many forecasts to one defensible decision.</h1><p className="mt-5 text-lg leading-8 text-slate-400">This is the product flow a jury can trace: signals arrive, context changes their credibility, AERIS explains the resulting decision, and verification improves the next one.</p></div>
    <section className="mt-12 rounded-3xl border border-cyan-400/20 bg-navy-900/80 p-5 shadow-2xl shadow-cyan-950/20 md:p-8"><Stage label="01 · FORECAST INPUTS" title="Do not discard disagreement—make it visible." cards={inputs} /><FlowArrow /><Stage label="02–04 · AERIS INTELLIGENCE LAYER" title="Context converts raw forecasts into calibrated trust." cards={intelligence} /><FlowArrow /><div className="grid gap-4 lg:grid-cols-[1.2fr_.8fr]"><div className="rounded-2xl border border-emerald-400/20 bg-emerald-400/5 p-6"><p className="text-xs font-bold tracking-[.18em] text-emerald-300">05 · DECISION PRODUCTS</p><h2 className="mt-2 text-xl font-semibold text-white">Forecast value, confidence, and the reason why.</h2><div className="mt-5 grid gap-3 sm:grid-cols-3">{[["Blended forecast", "Rainfall · temperature · wind"], ["Reliability story", "FRS · uncertainty · disagreement"], ["Action intelligence", "Extreme event cards · alerts"]].map(([a, b]) => <div key={a} className="rounded-xl bg-navy-950/70 p-3"><div className="text-sm font-medium text-white">{a}</div><div className="mt-1 text-xs leading-5 text-slate-400">{b}</div></div>)}</div></div><div className="rounded-2xl border border-amber-300/20 bg-amber-300/5 p-6"><ShieldAlert className="text-amber-200" /><h2 className="mt-3 font-semibold text-white">Human-in-the-loop</h2><p className="mt-2 text-sm leading-6 text-slate-400">AERIS supports—not replaces—official weather warnings and expert judgement.</p></div></div></section>
    <section className="mt-8 grid gap-5 lg:grid-cols-2"><article className="rounded-2xl border border-cyan-900/40 bg-navy-900 p-6"><p className="text-xs font-bold tracking-[.18em] text-cyan-300">CONTINUOUS LEARNING LOOP</p><h2 className="mt-2 text-xl font-semibold text-white">Tomorrow&apos;s trust learns from today&apos;s outcome.</h2><div className="mt-6 flex flex-wrap items-center gap-2 text-xs">{["Forecast", "Observed weather", "Error & skill", "Weight update", "Improved next forecast"].map((x, i) => <><span key={x} className="rounded-full border border-cyan-300/20 bg-cyan-300/5 px-3 py-2 text-cyan-100">{x}</span>{i < 4 && <ArrowRight key={`${x}-arrow`} size={14} className="text-cyan-400" />}</>)}</div></article><article className="rounded-2xl border border-cyan-900/40 bg-navy-900 p-6"><p className="text-xs font-bold tracking-[.18em] text-cyan-300">JURY WALKTHROUGH</p><h2 className="mt-2 text-xl font-semibold text-white">A clear five-minute demonstration.</h2><ol className="mt-5 space-y-3 text-sm text-slate-300">{["Overview: national picture and reliability", "Forecast Explorer: compare sources at one location", "Counterfactual Lab: remove a model and inspect impact", "Verification: prove the learning loop", "System Health: show the operational foundation"].map((x, i) => <li key={x} className="flex gap-3"><span className="font-mono text-cyan-300">0{i + 1}</span>{x}</li>)}</ol></article></section>
  </div></main>;
}

function FlowArrow() { return <div className="flex justify-center py-5"><ArrowDown className="text-cyan-300" size={24} /></div>; }
function Stage({ label, title, cards }: { label: string; title: string; cards: ReadonlyArray<readonly [string, string, typeof CloudRain]> }) { return <div><p className="text-xs font-bold tracking-[.18em] text-cyan-300">{label}</p><h2 className="mt-2 text-xl font-semibold text-white">{title}</h2><div className="mt-5 grid gap-3 md:grid-cols-4">{cards.map(([name, detail, Icon]) => <div key={name} className="rounded-2xl border border-white/10 bg-navy-950/70 p-4"><Icon size={20} className="text-cyan-300" /><h3 className="mt-4 text-sm font-semibold text-white">{name}</h3><p className="mt-1 text-xs leading-5 text-slate-400">{detail}</p><CheckCircle2 size={14} className="mt-4 text-emerald-300" /></div>)}</div></div>; }
